name: Waka Readme

on:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BAR_STYLE: "svg"
          BAR_COLOR: "#90CAF9"
          BAR_TRACK_COLOR: "#172f45"
          BAR_RADIUS: "4"
          TEXT_PRIMARY_COLOR: "#c9d1d9"
          TEXT_SECONDARY_COLOR: "#8b949e"